### ISSUE TITLE
what happens if canceled download the file?

### ISSUE THREAD

**Issue by Shekhrozx** [azavea/django-queryset-csv#103]
I am using `djqscsv.render_to_csv_response() `function to export my django querset to `*.csv` file. when I canceled downloading the ` *.csv` file, I got  error like that:
```
Exception happened during processing of request from ('127.0.0.1', 61041)
[12/Oct/2018 17:54:05] "POST /accounts/data_extraction/ HTTP/1.1" 200 2375804
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 279, in write
    self._write(data)
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\socket.py", line 594, in write
    return self._sock.send(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
[12/Oct/2018 17:54:05] "POST /accounts/data_extraction/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 279, in write
    self._write(data)
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\socket.py", line 594, in write
    return self._sock.send(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "D:\Company projects\websystem\truckcaliber\lib\site-packages\django\core\servers\basehttp.py", line 88, in handle_error
    super(ServerHandler, self).handle_error()
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\socketserver.py", line 681, in __init__
    self.handle()
  File "D:\Company projects\websystem\truckcaliber\lib\site-packages\django\core\servers\basehttp.py", line 155, in handle
    handler.run(self.server.get_app())
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "c:\users\user\appdata\local\programs\python\python35-32\Lib\wsgiref\simple_server.py", line 36, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

What is wrong there?

**Comment by maurizi** [comment]
This is a normal error to get in Django when a client cancels a connection.

We intentionally do not handle canceled connections as part of this library - if it is something you'd like to catch, I would suggest doing so at the application level (you may need to pass `streaming=False` to `render_to_csv_response` to be able to do so).

StackOverflow should have more information on how to handle aborted connections in your application.
