### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by cubiczx** [azavea/django-queryset-csv#72]
Problem with:
```
í	237	u’\xed’	\xc3\xad	\xed	Latin small i with acute
```
```shell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/xpalacin/Sites/django_guiaterapeutica/main/views.py", line 148, in get
    text = render_to_csv_response(queryset)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/djqscsv/djqscsv.py", line 49, in render_to_csv_response
    write_csv(queryset, response, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/djqscsv/djqscsv.py", line 122, in write_csv
    writer.writerow(merged_header_map)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/csv.py", line 148, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 1: ordinal not in range(128)
```

**Comment by steventlamb** [comment]
Djqscsv *should* utf8 encode all values. Can you post your model definition, and a printout of the value of `queryset` at/before:
```
File "/Users/xpalacin/Sites/django_guiaterapeutica/main/views.py", line 148, in get
```

**Comment by ddohler** [comment]
The exception is being raised when trying to write the header row, and it doesn't look like `merged_header_map` is being encoded to UTF-8 before being outputted, so I'd bet that's the source of the error.

**Comment by steventlamb** [comment]
A while back someone submitted a fix, https://github.com/azavea/django-queryset-csv/commit/8aa104aece3c8cae12581f60c422670ee40ea625, but it only encodes a few of the keys inside an if branch, in the case where the user ran into it.

I'll probably update it to always encode everything, but it would be nice to see some context anyway for more confidence.

**Comment by cubiczx** [comment]
The problem has been solved magically: 
models.py:
```python
#-*- encoding=UTF-8 -*-
class Anexo(models.Model):
    # Anexo Fields
    title = models.CharField(_(u'Título'), max_length=255)
    fichero = models.FileField(upload_to="anexos")
    orden = models.PositiveSmallIntegerField(default=0, blank=False, null=False)

    def __unicode__(self):
        return strip_tags(self.title)
```
views.py:
```python
#-*- encoding=UTF-8 -*-
class viewExport(View):
def get(self, request, export_type=None):
from djqscsv import render_to_csv_response
				models_list = [Abreviatura, Anexo, Archivo_medico, Circunstancia, CircunstanciaTratamiento, 
					Farmaco, Farmaco_anexo, Farmaco_farmaco_relacionado_id, Farmaco_ico_farmaco, Farmaco_problema_in_observaciones, Ico_farmaco, Medicamento,
					No_farmacologica, No_farmacologica_anexo_in_medida, No_farmacologica_problema_in_medida,
					Presentacion, Problema, Problema_anexo, Problema_anexo_in_observaciones, Problema_archivo_medico,
					Problema_in_observaciones, ProblemaTratamiento, Tipo_de_problema, Tratamiento, Tratamiento_anexo, 
					Tratamiento_Farmaco, Tratamiento_farmaco_problema_in_dosis, Tratamiento_problema_in_tratamiento]

				for model in models_list:
					queryset = model.objects.all()

					model_csv = ''
					model_csv = render_to_csv_response(queryset)
```
